name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5.0.1
        with:
          go-version: ">=1.22.2"
      - uses: actions/setup-python@v5

      - run: go install github.com/fzipp/gocyclo/cmd/gocyclo@latest
      - run: go install golang.org/x/tools/cmd/goimports@latest
      - run: go install github.com/go-critic/go-critic/cmd/gocritic@latest
      - run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.58.2
      - uses: pre-commit/action@v3.0.1
